"""Create reviewable FHIR proposals, not write requests."""

from __future__ import annotations

from pipelines.contracts import CandidateFact


def candidate_to_observation(fact: CandidateFact) -> dict:
    if fact.review_status != "approved":
        raise PermissionError("FHIR mapping requires an approved review decision")
    return {
        "resourceType": "Observation",
        "status": "preliminary",
        "code": {"text": fact.category},
        "valueString": fact.value,
        "note": [{"text": "Candidate generated by a research reference pipeline."}],
        "extension": [{
            "url": "https://example.org/fhir/StructureDefinition/source-provenance",
            "valueString": fact.evidence.document_sha256,
        }],
    }
